INSERT INTO TMK_MONEY_USER (USER_ID, CHAT_ROOM_ID) VALUES ('marduk', '9shKanauPo');
INSERT INTO TMK_MONEY_USER (USER_ID, CHAT_ROOM_ID) VALUES ('josie', '9shKanauPo');
INSERT INTO TMK_MONEY_USER (USER_ID, CHAT_ROOM_ID) VALUES ('king', '9shKanauPo');
INSERT INTO TMK_MONEY_USER (USER_ID, CHAT_ROOM_ID) VALUES ('katarina', '9shKanauPo');